# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Judo Club Agenais
email: contact@judoclubagenais.com
description: >- # this means to ignore newlines until "baseurl:"
  Club crée en 1948, le Judo Club Agenais a formé jusqu'à aujourd'hui plus d'une centaine de ceintures noires.
  Seul club de Judo-Jujitsu de la ville d'Agen, il se situe à Donnefort (quartier Nord-Est).
  L'objet de l'association est de contribuer à l'harmonieux épanouissement de chacun à travers la pratique du Judo, du Jujitsu et du Baby Judo.
baseurl: "" # the subpath of your site, e.g. /blog
url: # "http://judoclubagenais.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: judoclubagenais
github_username:  porko

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-autoprefixer


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
